#!/usr/bin/env python


# -------
# Imports
# -------

from argparse import ArgumentParser

from spectroscopy.utilities import eigenvectors_to_eigendisplacements

from spectroscopy.cli.io_helper import (
    write_structures_raman, read_dielectric_tensors)

from spectroscopy.cli.parser import update_parser, post_process_args

from spectroscopy.cli.phonopy_helper import (
    phonopy_update_parser, phonopy_load_core, phonopy_load_optional)
                                    
from spectroscopy.cli.runtime import (
    run_mode_raman_disp, run_mode_raman_read, run_mode_raman_postproc)


# ----
# Main
# ----

if __name__ == "__main__":
    # Parse command-line arguments.

    parser = ArgumentParser(
        description="Simulate Raman spectra starting from a Phonopy "
                    "calculation")

    # Add standard Phonopy argument groups.

    phonopy_update_parser(parser, 'raman')

    # Add standard arguments groups.

    update_parser(parser, 'raman', supported_features=['irreps'])

    # Parse and process arguments.

    args = parser.parse_args()

    post_process_args(args, 'raman')

    # If creating displacements, read the structure, atomic masses and
    # Gamma-point frequencies/eigenvectors.

    structure = None
    frequencies, eigendisplacements = None, None

    if args.RunMode == 'raman_disp':
        # Read input data.

        input_data = phonopy_load_core(
            args, extract_list=['structure', 'atomic_masses', 'phonon_modes'])

        structure = input_data['structure']

        frequencies, eigenvectors = input_data['phonon_modes']

        # Convert eigenvectors to eigendisplacements.

        eigendisplacements = eigenvectors_to_eigendisplacements(
            eigenvectors, input_data['atomic_masses'])

    # If post-processing, read the ir. rep. data and/or linewidths if
    # required.

    line_widths, irrep_data = None, None

    if args.RunMode == 'raman_postproc':
        linewidths, irrep_data = phonopy_load_optional(args)

    # Hand over to one of the RunMode_Raman_*() routines.

    if args.RunMode is None:
        raise Exception(
            "Error: Please specify a run mode with one of the "
            "-d/--create_disp, -r/--read or -p/--post_process options.")

    elif args.RunMode == 'raman_disp':
        disp_sets = run_mode_raman_disp(
            structure, frequencies, 'thz', eigendisplacements, args)

        write_structures_raman(
            disp_sets, file_format='vasp_poscar',
            output_prefix=args.OutputPrefix)

    elif args.RunMode == 'raman_read':
        eps_tensors = read_dielectric_tensors(
            args.RamanInputFiles, file_format='vasp_outcar'
            )

        run_mode_raman_read(eps_tensors, args)

    elif args.RunMode == 'raman_postproc':
        run_mode_raman_postproc(
            args, linewidths=linewidths, irrep_data=irrep_data)
